import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Home from "../app/components/screens/home/Home";

const HomePage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Simple shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </div>
  );
};

export default HomePage;
